### ISSUE TITLE
ошибка: expected identifier or «(» before «do»

### ISSUE THREAD

**Issue by parmax** [ruslashev/voproxyd#2]
# make prepare-onvif
unzip deps/gsoap_2.8.74.zip
configure gsoap
make gsoap
install gsoap
wsdl2h -o deps/onvif/onvif.h
soapcpp2 deps/onvif/onvif.h
soapcpp2 deps/gsoap-2.8/gsoap/import/wsdd5.h
copy gsoap sources
move nsmaps

# make
cc avltree.c
cc bridge_commands.c
cc bridge_inquiries.c
cc buffer.c
cc config.c
cc daemonize.c
cc epoll.c
cc main.c
In file included from main.c:4:0:
log.h:17:5: ошибка: expected identifier or «(» before «do»
     do { \
     ^
log.h:22:7: ошибка: expected identifier or «(» before «while»
     } while (0)
       ^
make: *** [Makefile:75: .obj/main.c.o] Ошибка 1

**Comment by parmax** [comment]
Когда я поменял порядок include в main.c он собрался, но потом еще в soap_utils.h
Но всё равно не собирается с таким веером:
 soap_instance.c: В функции «soap_instance_construct»:
soap_instance.c:9:9: предупреждение: implicit declaration of function «die»; did you mean «div»? [-Wimplicit-function-declaration]
         die(1, "failed to create soap instance");
         ^~~
         div
In file included from deps/onvif/soapStub.h:57:0,
                 from deps/onvif/soapH.h:16,
                 from soap_instance.h:3,
                 from soap_instance.c:1:
soap_instance.c: В функции «soap_instance_destruct»:
soap_instance.c:16:18: ошибка: «soap» не описан (первое использование в этой функции)
     soap_destroy(soap);
                  ^
deps/onvif/stdsoap2.h:3087:41: замечание: in definition of macro «soap_destroy»
 #define soap_destroy(soap) soap_delete((soap), NULL)
                                         ^~~~
soap_instance.c:16:18: замечание: сообщение о каждом неописанном идентификаторе выдается один раз в каждой функции, где он встречается
     soap_destroy(soap);
                  ^
deps/onvif/stdsoap2.h:3087:41: замечание: in definition of macro «soap_destroy»
 #define soap_destroy(soap) soap_delete((soap), NULL)
                                         ^~~~
make: *** [Makefile:75: .obj/soap_instance.c.o] Ошибка 1

**Comment by rbakbashev** [comment]
one question: why are you interested in this project?

**Comment by parmax** [comment]
Я искал прокси, который позволил бы использовать onvif камеры с vMix-ом.

**Comment by rbakbashev** [comment]
1. ok. I'm glad that there's interest in the project. sad news is that it is not finished yet and is not in a working state. good news is that it is planned to be finished soon.

2. this is an international site, please stick to english.

3. I'm not interested in doing tech support when the project is not released. it contains bugs because master is unstable and that's on purpose

**Comment by parmax** [comment]
I would like to help as much as possible

**Comment by rbakbashev** [comment]
thank you for your concern, but actually no need to, because this project is part of work for my university. I have a vision and roadmap of what needs to be done and it's not that big, plus I have deadlines, so you may not worry about project being abandoned or unfinished.
